/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChinhSachRouteImport } from './routes/chinh-sach'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DieuKhoanRouteImport } from './routes/dieu-khoan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachRoute = ChinhSachRouteImport.update({
  id: '/chinh-sach',
  path: '/chinh-sach',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuKhoanRoute = DieuKhoanRouteImport.update({
  id: '/dieu-khoan',
  path: '/dieu-khoan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chinh-sach': typeof ChinhSachRoute
  '/demo': typeof DemoRoute
  '/dieu-khoan': typeof DieuKhoanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chinh-sach': typeof ChinhSachRoute
  '/demo': typeof DemoRoute
  '/dieu-khoan': typeof DieuKhoanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chinh-sach': typeof ChinhSachRoute
  '/demo': typeof DemoRoute
  '/dieu-khoan': typeof DieuKhoanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chinh-sach' | '/demo' | '/dieu-khoan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chinh-sach' | '/demo' | '/dieu-khoan'
  id: '__root__' | '/' | '/chinh-sach' | '/demo' | '/dieu-khoan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChinhSachRoute: typeof ChinhSachRoute
  DemoRoute: typeof DemoRoute
  DieuKhoanRoute: typeof DieuKhoanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach': {
      id: '/chinh-sach'
      path: '/chinh-sach'
      fullPath: '/chinh-sach'
      preLoaderRoute: typeof ChinhSachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-khoan': {
      id: '/dieu-khoan'
      path: '/dieu-khoan'
      fullPath: '/dieu-khoan'
      preLoaderRoute: typeof DieuKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChinhSachRoute: ChinhSachRoute,
  DemoRoute: DemoRoute,
  DieuKhoanRoute: DieuKhoanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
